name: gen_lang
description:
version: 0.1.0
author: King Wu (@kw101)
homepage:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  args: '>=0.12.1 <2.0.0'
  path: '>=0.9.0 <2.0.0'
  ansicolor: 1.0.2